spring:
  application:
    name: @project.name@
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8100
          predicates:
            - Path=/users/**

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    service-url: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}